version: "3.8"
services:
  my-mongodb:
    image: mongo:6-jammy
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # named volumes
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  postgres:
    image: "postgres:16.1"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "distcomp" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  kafka:
    image: confluentinc/cp-kafka:7.5.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_INTERNAL_ADVERTISED_LISTENER},${KAFKA_EXTERNAL_ADVERTISED_LISTENER}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LISTENERS: ${KAFKA_INTERNAL_ADVERTISED_LISTENER},${KAFKA_CONTROLLER_LISTENER},${KAFKA_PLAINTEXT_LISTENER}
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      CLUSTER_ID: X1oISRwqQ1yqeRlIjsegqQ
    volumes:
      - kafka-data:/var/lib/kafka/data


volumes:
  db-data:
    driver: local
  kafka-data:
    driver: local
  mongo-data:
    driver: local
  mongo-config:
    driver: local